M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu20.04.1} date ven. 08 juil. 2022 20:06:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-08T20:06:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X92.71Y-54.44
X98.49Y-54.44
T0
M30
